### ISSUE TITLE
Errr plz help

### ISSUE THREAD

**Issue by kumawatrohit537** [mohinparamasivam/Email-Bomber#15]
File "/data/data/com.termux/files/home/Email_Bomber/emailbomber3.py", line 44
    Cport = input('Custom smtp port (leave blank to use defaul port): '))
                                                                        ^
SyntaxError: unmatched ')'

**Comment by Omicron166** [comment]
how did that ")" get to the code?

In any case, in a few hours I'm going to get a pull request solving that typo, thanks for reporting the bug
