### ISSUE TITLE
print error

### ISSUE THREAD

**Issue by yungburrito** [mohinparamasivam/Email-Bomber#17]
I followed the directions given, but got the following error:
**  File "C:\Users\USER\Downloads\Email-Bomber-master\emailbomber.py", line 14
    print '                                                                    '
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?**

I see that it says usr/bin/python, is this solely for linux?

**Comment by Omicron166** [comment]
use emailbomber3.py instead of emailbomber.py

and it works on windows and linux
