### ISSUE TITLE
user name & password error 

### ISSUE THREAD

**Issue by brainhacker3458** [mohinparamasivam/Email-Bomber#19]
There is a syntax error. This user name & password or smtp server error.
![Opinion](https://user-images.githubusercontent.com/97605498/149610466-ba39d10c-2d10-4f08-a820-706cb7aea487.jpg)

**Comment by clinton2710** [comment]
enable less secure apps oin your google settings

**Comment by Omicron166** [comment]
Enable less secure apps on your google account with this link

https://myaccount.google.com/lesssecureapps
