### ISSUE TITLE
Incorrect username and password

### ISSUE THREAD

**Issue by CodeGrillsGuru** [mohinparamasivam/Email-Bomber#2]
Fake tool😤😤😤😤

**Comment by Omicron166yt** [comment]
@gurugrover the tool is affected by gmail security (if you are using a gmail account).
Please check the code yourself before commenting those things.

A solution to this problem can be to create your own stmp server temporarily and use an email from it to attack

**Comment by x44uarbdx** [comment]
> @gurugrover the tool is affected by gmail security (if you are using a gmail account).
> Please check the code yourself before commenting those things.
> 
> A solution to this problem can be to create your own stmp server temporarily and use an email from it to attack

But Then The Mail Will Be In Spam

**Comment by nkb20** [comment]
What is user id and password??

**Comment by cheyao** [comment]
@nkb20 you email and its password

**Comment by Omicron166** [comment]
remember to follow the new instructions on the readme
