### ISSUE TITLE
FAKE TOOL FOR COLLECTING ID & PASSWORD OF GMAIL

### ISSUE THREAD

**Issue by blackhacker1101** [mohinparamasivam/Email-Bomber#25]

**Comment by Omicron166** [comment]
We don't collect passwords, please check the source code

**Comment by Omicron166** [comment]
@mohinparamasivam mentions in [pull #26](https://github.com/mohinparamasivam/Email-Bomber/pull/26#issuecomment-1169904114) a new method to keep supporting gmail, i'm writing the new instructions right now so, yes

**Comment by Omicron166** [comment]
i don't use whatsapp, do you have twitter or telegram?

**Comment by Omicron166** [comment]
I have Telegram, Twitter and Discord

**Comment by Omicron166** [comment]
I don't know how to add someone with the id, message me pls https://t.me/omicron166
